from pwdlib import PasswordHash
from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.models.user import User


# ---------------------------------------------------------
# PASSWORD HASHING
# ---------------------------------------------------------

password_hash = PasswordHash.recommended()


# ---------------------------------------------------------
# ADMIN CONFIG
# ---------------------------------------------------------

ADMIN_NAME = "System Admin"
ADMIN_EMAIL = "admin@test.com"
ADMIN_PASSWORD = "Admin@12345"


# ---------------------------------------------------------
# CREATE / UPDATE ADMIN
# ---------------------------------------------------------

def create_admin():
    db: Session = SessionLocal()

    try:
        existing_user = (
            db.query(User)
            .filter(User.email == ADMIN_EMAIL)
            .first()
        )

        if existing_user:
            print(f"Admin already exists: {ADMIN_EMAIL}")

            # Make sure the existing account is an admin
            existing_user.name = ADMIN_NAME
            existing_user.role = "admin"

            # IMPORTANT:
            # Replace the old bcrypt password with an Argon2
            # password hash generated by pwdlib.
            existing_user.password_hash = password_hash.hash(
                ADMIN_PASSWORD
            )

            db.commit()
            db.refresh(existing_user)

            print("Existing admin updated successfully.")
            print(f"ID: {existing_user.id}")
            print(f"Email: {existing_user.email}")
            print(f"Role: {existing_user.role}")

        else:
            admin = User(
                name=ADMIN_NAME,
                email=ADMIN_EMAIL,
                password_hash=password_hash.hash(
                    ADMIN_PASSWORD
                ),
                role="admin",
                resume_url=None
            )

            db.add(admin)
            db.commit()
            db.refresh(admin)

            print("Admin created successfully.")
            print(f"ID: {admin.id}")
            print(f"Email: {admin.email}")
            print(f"Role: {admin.role}")

    except Exception as e:
        db.rollback()
        print(f"Error: {e}")
        raise

    finally:
        db.close()


if __name__ == "__main__":
    create_admin()